package com.p20241061.shared.models.enums;

public enum ErrorCode {
    DEFAULT_ERROR,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    CONFLICT,
    NOT_IMPLEMENTED,
    BAD_GATEWAY,
    UNKNOWN_ERROR,
    ALREADY_EXISTS,
}